[package]
name = "life_game_in_rust"
version = "0.1.0"
authors = ["hogehoge1298 <hogehoge1298@gmail.com>"]

[dependencies]
piston = "0.31.1"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.0"